version: "3.8"
services:
  api-service:
    image: restapi
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - api-database


  api-database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
